name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.202.151.231 << 'EOF'
        cd next-portfolio
        git pull origin main
        rm -rf .next
        npm install
        npm run build
        
        # Install PM2 if not already installed
        pm2 --version || npm install -g pm2

        # Stop the previous instance of the app
        pm2 stop next-portfolio || true

        # Start the app with PM2
        pm2 start npm --name "next-portfolio" -- start

        # Save the PM2 process list to restart after reboot
        pm2 save

        sudo systemctl restart nginx
        exit
        EOF